### ISSUE TITLE
Project Overview: Smaller Design Issues

### ISSUE THREAD

**Issue by KathaH** [anfema/website#458]
- [x] Anfema-Card: please fix a-element / email
- [x] Anfema-Card: please change hover (-saturation). @ginamalchar provides the layout
- [x] Header "Projects" not clickable, please change it to an a-element

Assets
- MyStaffPilot: tablet und phone missing

Assets Mobil
- [x] Phone assets should be displayed as a whole - not cropped

**Comment by ginamalchar** [comment]
@sariita05 Here's the zeplin section for the project overview: zpl://project?pid=59a92c06d5e0846b848b74f8&seid=5fdcc55742636219b3f0ce08
