### ISSUE TITLE
Project-Detailpage: MyStaffPilot

### ISSUE THREAD

**Issue by KathaH** [anfema/website#459]
- [x] Top-Features component shouldn't be displayed
- [x] missing contact module
- [x] missing quote module: https://projects.invisionapp.com/d/main?origin=v7#/console/19870023/419580529/preview?scrollOffset=2357 since the quote is quiet long, my suggestion would be to divide it into a large text and a small text underneath. The cut could be by "...Promotion-Jobs bietet". @ginamalchar  could you please provide a design for that? merci!

**Comment by ginamalchar** [comment]
@sariita05 Here's the zeplin section for MyStaffPilot: zpl://project?pid=59a92c06d5e0846b848b74f8&seid=601161e34f8fdf29de81ca0a
