### ISSUE TITLE
Project Detailpage: Smaller Design + Text Issues

### ISSUE THREAD

**Issue by KathaH** [anfema/website#460]
- [x] Quote-Module: please check font weight, should be semibold not bold @ginamalchar uploads the pages in zeplin 
- [x] Technology-Module: horizontal alignment: please align the icons on the left side, not stretched 
<img width="633" alt="Bildschirmfoto 2021-01-27 um 11 34 33" src="https://user-images.githubusercontent.com/57345487/105979173-a5059e80-6093-11eb-9598-a5b39772091e.png">

Pingonaut
- [ ] module: all about the details -> missing description 

Frechau
- [x] please check breaks and delete "br" e.g.(mobile) "how we made it awesome" / "technology we used"
<img width="509" alt="Bildschirmfoto 2021-01-27 um 11 42 08" src="https://user-images.githubusercontent.com/57345487/105980103-be5b1a80-6094-11eb-8530-ceee5e2f141d.png">

Audi
- [x] no asset rotation in the first section
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/57345487/105980982-d3847900-6095-11eb-807b-9964d389fdd8.png">
Please check what happened with all the assets at the Audi page:
- [ ]they are way to small..  :D  https://www-dev.anfe.ma/de/projects/audi

IDnow
- [x] please check angle of assets. @ginamalchar could please add how it should look like? 
<img width="472" alt="image" src="https://user-images.githubusercontent.com/57345487/105980524-43463400-6095-11eb-8226-d7a855fd884d.png">

Mobile: Technology we used module
- [x] Icons are too large at Ferchau, Paulaner, Audi, Knauf, TODs, IDnow, Pingonaut, BMW please check with @ginamalchar

**Comment by ginamalchar** [comment]
@sariita05 You can see the designs in the different zeplin sections of the detail pages for each project. 

e.g.
- Audi: zpl://project?seid=601154a73b2d227e799d4a70&pid=59a92c06d5e0846b848b74f8
- IDnow: zpl://project?seid=60115bafcf90c81014852aeb&pid=59a92c06d5e0846b848b74f8
- Ferchau: zpl://project?seid=60115b5f94a12a2a7c6b0f8c&pid=59a92c06d5e0846b848b74f8
