### ISSUE TITLE
Smaller Design- und Text-Issues

### ISSUE THREAD

**Issue by KathaH** [anfema/website#469]
**EN**
- [x] Projektdetailseite: email placeholder-Text bitte ergänzen, ist momentan nicht ganz ;) 

**Generell** 
- [x] Fehlender Text bei Allgemeiner Kontakt E-Mail-Verlinkung
Vorschlag Deutsch: 
Liebes Anfema-Team, eure Projekte klingen super spannend! Sehr gerne würde ich mehr über das eine oder andere Projekt erfahren. Ich würde mich über einen Terminvorschlag für ein Telefonat, eine Webkonferenz oder irgendwann wieder in Person sehr freuen! 
Viele Grüße, 

Vorschlag Englisch: 
Dear Anfema-Team, 
you're projects are awesome! Let's have a chat via telephone, web or maybe in person - in the nearly future ;) 
See you soon,

**Mobile**
- [x] wenn man von der Projekt-Übersicht kommt und dann bspw auf MSP oder Knauf klickt, startet man nicht am Anfang der Seite, sondern einfach mittendrin

**Comment by ginamalchar** [comment]
**Projektübersicht** 
- [ ] "Du willst mehr sehen?" Link zur Mail sollte auf dem Wort "E-Mail" sein (siehe https://github.com/anfema/website/issues/462)
- [ ] Es sind aktuell nicht alle Projekte zu sehen, gibt es dafür einen Grund? (BCG, Knauf ARoom fehlen) 
- [ ] Andordnung der Projekte bei Tablet/Mobile passt nicht ganz - zu viel Orange und Rot direkt nacheinander. 
-> bitte wenn möglich so: 
![Mobile](https://user-images.githubusercontent.com/53598256/107927541-6fa7ee80-6f77-11eb-9eec-274f02ec2359.jpg)
![Tablet](https://user-images.githubusercontent.com/53598256/107927545-70d91b80-6f77-11eb-8e97-7e8b25eb9e77.jpg)

 **Projekt-Detail** 
- [ ] Technology - Mobile: Icons sind generell etwas klein 
![dev](https://user-images.githubusercontent.com/53598256/107928211-57849f00-6f78-11eb-888a-a543962d0c6e.png)

Sollten größer sein: 
![design](https://user-images.githubusercontent.com/53598256/107928259-623f3400-6f78-11eb-8c71-25719550d512.png)

- [ ] Audi - Tablet: Mockup ist unten rechts nicht ganz angeschnitten, es entsteht ein unschöner Blitzer, wenn möglich bitte fixen. Die Schriftgröße erscheint hier auch recht klein - bitte generell prüfen, sollte 90 sein
![image](https://user-images.githubusercontent.com/53598256/107928671-ea253e00-6f78-11eb-9456-95e5acf0f503.png)
