### ISSUE TITLE
Update Project Overview

### ISSUE THREAD

**Issue by ginamalchar** [anfema/website#494]
Da BCG nicht auf der Website veröffentlicht werden darf, muss das Projekt auch aus der Übersicht raus. Dadurch ändert sich das Laylout und muss entsprechend angepasst werden. 

Die Screens sind in Figma aktualisiert. (https://www.figma.com/file/BBHqHXMtHgGignPMtp6j0f/Website?node-id=81%3A20468

Hier noch zur Übersicht: 
- Desktop: 
![Desktop](https://user-images.githubusercontent.com/53598256/111458236-8168e700-8719-11eb-8f05-7a350dc7b4cb.jpg)

- Tablet: 
![Tablet](https://user-images.githubusercontent.com/53598256/111458270-89c12200-8719-11eb-9103-998235797dc1.jpg)

- Mobile: 
![Mobile](https://user-images.githubusercontent.com/53598256/111458300-8fb70300-8719-11eb-9d13-186023092f16.jpg)

**Comment by rollacting** [comment]
MYSTAFFPILOT als Name bitte immer (außer natürlich bei weblinks wie www.mystaffpilot.de ) groß schreiben. nicht "MyStaffPilot"!!.
